name: CI with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t qa-tester .

    - name: Run tests in container
      run: docker run qa-tester

  deploy:
    runs-on: ubuntu-latest
    needs: test   # 🔥 rất quan trọng

    steps:
      - name: Mock Deploy
        run: echo "Deploying to staging..."